export type TraceChar = {
  id: string;
  character: string;
  reading: string;
  meaning?: string;
};

export type TraceSet = "hiragana" | "katakana" | "kanji-n5";

export const TRACE_DATA: Record<TraceSet, TraceChar[]> = {
  hiragana: [
    { id: "h-a",  character: "あ", reading: "a"  },
    { id: "h-i",  character: "い", reading: "i"  },
    { id: "h-u",  character: "う", reading: "u"  },
    { id: "h-e",  character: "え", reading: "e"  },
    { id: "h-o",  character: "お", reading: "o"  },
    { id: "h-ka", character: "か", reading: "ka" },
    { id: "h-ki", character: "き", reading: "ki" },
    { id: "h-ku", character: "く", reading: "ku" },
    { id: "h-ke", character: "け", reading: "ke" },
    { id: "h-ko", character: "こ", reading: "ko" },
    { id: "h-sa", character: "さ", reading: "sa" },
    { id: "h-si", character: "し", reading: "shi" },
    { id: "h-su", character: "す", reading: "su" },
    { id: "h-se", character: "せ", reading: "se" },
    { id: "h-so", character: "そ", reading: "so" },
    { id: "h-ta", character: "た", reading: "ta" },
    { id: "h-ti", character: "ち", reading: "chi" },
    { id: "h-tu", character: "つ", reading: "tsu" },
    { id: "h-te", character: "て", reading: "te" },
    { id: "h-to", character: "と", reading: "to" },
    { id: "h-na", character: "な", reading: "na" },
    { id: "h-ni", character: "に", reading: "ni" },
    { id: "h-nu", character: "ぬ", reading: "nu" },
    { id: "h-ne", character: "ね", reading: "ne" },
    { id: "h-no", character: "の", reading: "no" },
    { id: "h-ha", character: "は", reading: "ha" },
    { id: "h-hi", character: "ひ", reading: "hi" },
    { id: "h-hu", character: "ふ", reading: "fu" },
    { id: "h-he", character: "へ", reading: "he" },
    { id: "h-ho", character: "ほ", reading: "ho" },
    { id: "h-ma", character: "ま", reading: "ma" },
    { id: "h-mi", character: "み", reading: "mi" },
    { id: "h-mu", character: "む", reading: "mu" },
    { id: "h-me", character: "め", reading: "me" },
    { id: "h-mo", character: "も", reading: "mo" },
    { id: "h-ya", character: "や", reading: "ya" },
    { id: "h-yu", character: "ゆ", reading: "yu" },
    { id: "h-yo", character: "よ", reading: "yo" },
    { id: "h-ra", character: "ら", reading: "ra" },
    { id: "h-ri", character: "り", reading: "ri" },
    { id: "h-ru", character: "る", reading: "ru" },
    { id: "h-re", character: "れ", reading: "re" },
    { id: "h-ro", character: "ろ", reading: "ro" },
    { id: "h-wa", character: "わ", reading: "wa" },
    { id: "h-wo", character: "を", reading: "wo" },
    { id: "h-n",  character: "ん", reading: "n"  },
  ],
  katakana: [
    { id: "k-a",  character: "ア", reading: "a"   },
    { id: "k-i",  character: "イ", reading: "i"   },
    { id: "k-u",  character: "ウ", reading: "u"   },
    { id: "k-e",  character: "エ", reading: "e"   },
    { id: "k-o",  character: "オ", reading: "o"   },
    { id: "k-ka", character: "カ", reading: "ka"  },
    { id: "k-ki", character: "キ", reading: "ki"  },
    { id: "k-ku", character: "ク", reading: "ku"  },
    { id: "k-ke", character: "ケ", reading: "ke"  },
    { id: "k-ko", character: "コ", reading: "ko"  },
    { id: "k-sa", character: "サ", reading: "sa"  },
    { id: "k-si", character: "シ", reading: "shi" },
    { id: "k-su", character: "ス", reading: "su"  },
    { id: "k-se", character: "セ", reading: "se"  },
    { id: "k-so", character: "ソ", reading: "so"  },
    { id: "k-ta", character: "タ", reading: "ta"  },
    { id: "k-ti", character: "チ", reading: "chi" },
    { id: "k-tu", character: "ツ", reading: "tsu" },
    { id: "k-te", character: "テ", reading: "te"  },
    { id: "k-to", character: "ト", reading: "to"  },
    { id: "k-na", character: "ナ", reading: "na"  },
    { id: "k-ni", character: "ニ", reading: "ni"  },
    { id: "k-nu", character: "ヌ", reading: "nu"  },
    { id: "k-ne", character: "ネ", reading: "ne"  },
    { id: "k-no", character: "ノ", reading: "no"  },
    { id: "k-ha", character: "ハ", reading: "ha"  },
    { id: "k-hi", character: "ヒ", reading: "hi"  },
    { id: "k-hu", character: "フ", reading: "fu"  },
    { id: "k-he", character: "ヘ", reading: "he"  },
    { id: "k-ho", character: "ホ", reading: "ho"  },
    { id: "k-ma", character: "マ", reading: "ma"  },
    { id: "k-mi", character: "ミ", reading: "mi"  },
    { id: "k-mu", character: "ム", reading: "mu"  },
    { id: "k-me", character: "メ", reading: "me"  },
    { id: "k-mo", character: "モ", reading: "mo"  },
    { id: "k-ya", character: "ヤ", reading: "ya"  },
    { id: "k-yu", character: "ユ", reading: "yu"  },
    { id: "k-yo", character: "ヨ", reading: "yo"  },
    { id: "k-ra", character: "ラ", reading: "ra"  },
    { id: "k-ri", character: "リ", reading: "ri"  },
    { id: "k-ru", character: "ル", reading: "ru"  },
    { id: "k-re", character: "レ", reading: "re"  },
    { id: "k-ro", character: "ロ", reading: "ro"  },
    { id: "k-wa", character: "ワ", reading: "wa"  },
    { id: "k-wo", character: "ヲ", reading: "wo"  },
    { id: "k-n",  character: "ン", reading: "n"   },
  ],
  "kanji-n5": [
    { id: "kj-hi",  character: "日", reading: "にち / ひ",  meaning: "sun / day"     },
    { id: "kj-ge",  character: "月", reading: "げつ / つき", meaning: "moon / month"  },
    { id: "kj-ka",  character: "火", reading: "か / ひ",    meaning: "fire"           },
    { id: "kj-mi",  character: "水", reading: "すい / みず", meaning: "water"          },
    { id: "kj-mo",  character: "木", reading: "もく / き",  meaning: "tree / wood"    },
    { id: "kj-ki",  character: "金", reading: "きん / かね", meaning: "gold / money"   },
    { id: "kj-do",  character: "土", reading: "ど / つち",  meaning: "earth / soil"   },
    { id: "kj-ya",  character: "山", reading: "さん / やま", meaning: "mountain"        },
    { id: "kj-ka2", character: "川", reading: "かわ",        meaning: "river"           },
    { id: "kj-ta",  character: "田", reading: "た / でん",  meaning: "rice field"      },
    { id: "kj-hi2", character: "人", reading: "じん / ひと", meaning: "person"          },
    { id: "kj-ku",  character: "口", reading: "くち",        meaning: "mouth"           },
    { id: "kj-me",  character: "目", reading: "め / もく",  meaning: "eye"             },
    { id: "kj-mi2", character: "耳", reading: "みみ",        meaning: "ear"             },
    { id: "kj-te",  character: "手", reading: "て / しゅ",  meaning: "hand"            },
    { id: "kj-as",  character: "足", reading: "あし / そく", meaning: "foot / leg"      },
    { id: "kj-da",  character: "大", reading: "だい / おお", meaning: "big / large"     },
    { id: "kj-sho", character: "小", reading: "しょう / ちい", meaning: "small"         },
    { id: "kj-jo",  character: "上", reading: "うえ / じょう", meaning: "above / up"   },
    { id: "kj-ge2", character: "下", reading: "した / か",  meaning: "below / down"    },
    { id: "kj-na",  character: "中", reading: "なか / ちゅう", meaning: "middle / inside" },
    { id: "kj-ho",  character: "本", reading: "ほん / もと", meaning: "book / origin"   },
    { id: "kj-ko",  character: "子", reading: "こ / し",    meaning: "child"           },
    { id: "kj-on",  character: "女", reading: "おんな / じょ", meaning: "woman"         },
    { id: "kj-ot",  character: "男", reading: "おとこ / だん", meaning: "man"           },
  ],
};

export const SET_META: Record<TraceSet, { label: string; description: string; color: string; bg: string; count: number }> = {
  hiragana:   { label: "Hiragana",  description: "The basic Japanese syllabary", color: "#6C63FF", bg: "#F0EEFF", count: TRACE_DATA.hiragana.length   },
  katakana:   { label: "Katakana",  description: "Used for foreign words",       color: "#4C8BF5", bg: "#E6F0FF", count: TRACE_DATA.katakana.length   },
  "kanji-n5": { label: "Kanji N5",  description: "Essential beginner kanji",     color: "#30C06E", bg: "#E8F7EE", count: TRACE_DATA["kanji-n5"].length },
};
