export type VocabCard = {
  id: string;
  japanese: string;
  reading: string;
  english: string;
  example?: string;
};

export type JLPTLevel = "N5" | "N4" | "N3" | "N2" | "N1";

export const VOCAB: Record<JLPTLevel, VocabCard[]> = {
  N5: [
    { id: "n5-1",  japanese: "水",       reading: "みず",           english: "water" },
    { id: "n5-2",  japanese: "食べる",   reading: "たべる",         english: "to eat" },
    { id: "n5-3",  japanese: "飲む",     reading: "のむ",           english: "to drink" },
    { id: "n5-4",  japanese: "行く",     reading: "いく",           english: "to go" },
    { id: "n5-5",  japanese: "来る",     reading: "くる",           english: "to come" },
    { id: "n5-6",  japanese: "見る",     reading: "みる",           english: "to see / watch" },
    { id: "n5-7",  japanese: "聞く",     reading: "きく",           english: "to listen / ask" },
    { id: "n5-8",  japanese: "話す",     reading: "はなす",         english: "to speak" },
    { id: "n5-9",  japanese: "大きい",   reading: "おおきい",       english: "big" },
    { id: "n5-10", japanese: "小さい",   reading: "ちいさい",       english: "small" },
    { id: "n5-11", japanese: "新しい",   reading: "あたらしい",     english: "new" },
    { id: "n5-12", japanese: "古い",     reading: "ふるい",         english: "old" },
    { id: "n5-13", japanese: "高い",     reading: "たかい",         english: "tall / expensive" },
    { id: "n5-14", japanese: "安い",     reading: "やすい",         english: "cheap" },
    { id: "n5-15", japanese: "友達",     reading: "ともだち",       english: "friend" },
    { id: "n5-16", japanese: "学校",     reading: "がっこう",       english: "school" },
    { id: "n5-17", japanese: "先生",     reading: "せんせい",       english: "teacher" },
    { id: "n5-18", japanese: "学生",     reading: "がくせい",       english: "student" },
    { id: "n5-19", japanese: "今日",     reading: "きょう",         english: "today" },
    { id: "n5-20", japanese: "明日",     reading: "あした",         english: "tomorrow" },
  ],
  N4: [
    { id: "n4-1",  japanese: "運動",     reading: "うんどう",       english: "exercise / sport" },
    { id: "n4-2",  japanese: "練習",     reading: "れんしゅう",     english: "practice" },
    { id: "n4-3",  japanese: "準備",     reading: "じゅんび",       english: "preparation" },
    { id: "n4-4",  japanese: "説明",     reading: "せつめい",       english: "explanation" },
    { id: "n4-5",  japanese: "文化",     reading: "ぶんか",         english: "culture" },
    { id: "n4-6",  japanese: "経験",     reading: "けいけん",       english: "experience" },
    { id: "n4-7",  japanese: "意味",     reading: "いみ",           english: "meaning" },
    { id: "n4-8",  japanese: "理由",     reading: "りゆう",         english: "reason" },
    { id: "n4-9",  japanese: "場合",     reading: "ばあい",         english: "case / situation" },
    { id: "n4-10", japanese: "心配",     reading: "しんぱい",       english: "worry / concern" },
    { id: "n4-11", japanese: "大切",     reading: "たいせつ",       english: "important / precious" },
    { id: "n4-12", japanese: "特別",     reading: "とくべつ",       english: "special" },
    { id: "n4-13", japanese: "普通",     reading: "ふつう",         english: "normal / ordinary" },
    { id: "n4-14", japanese: "自分",     reading: "じぶん",         english: "oneself" },
    { id: "n4-15", japanese: "お互い",   reading: "おたがい",       english: "each other / mutual" },
    { id: "n4-16", japanese: "集める",   reading: "あつめる",       english: "to collect" },
    { id: "n4-17", japanese: "変える",   reading: "かえる",         english: "to change" },
    { id: "n4-18", japanese: "続ける",   reading: "つづける",       english: "to continue" },
    { id: "n4-19", japanese: "決める",   reading: "きめる",         english: "to decide" },
    { id: "n4-20", japanese: "送る",     reading: "おくる",         english: "to send" },
  ],
  N3: [
    { id: "n3-1",  japanese: "印象",     reading: "いんしょう",     english: "impression" },
    { id: "n3-2",  japanese: "影響",     reading: "えいきょう",     english: "influence / effect" },
    { id: "n3-3",  japanese: "可能",     reading: "かのう",         english: "possible" },
    { id: "n3-4",  japanese: "期待",     reading: "きたい",         english: "expectation / hope" },
    { id: "n3-5",  japanese: "状況",     reading: "じょうきょう",   english: "situation / circumstances" },
    { id: "n3-6",  japanese: "性格",     reading: "せいかく",       english: "personality / character" },
    { id: "n3-7",  japanese: "態度",     reading: "たいど",         english: "attitude / manner" },
    { id: "n3-8",  japanese: "判断",     reading: "はんだん",       english: "judgment / decision" },
    { id: "n3-9",  japanese: "雰囲気",   reading: "ふんいき",       english: "atmosphere / mood" },
    { id: "n3-10", japanese: "目的",     reading: "もくてき",       english: "purpose / goal" },
    { id: "n3-11", japanese: "優しい",   reading: "やさしい",       english: "kind / gentle" },
    { id: "n3-12", japanese: "珍しい",   reading: "めずらしい",     english: "rare / unusual" },
    { id: "n3-13", japanese: "厳しい",   reading: "きびしい",       english: "strict / harsh" },
    { id: "n3-14", japanese: "正直",     reading: "しょうじき",     english: "honest" },
    { id: "n3-15", japanese: "適当",     reading: "てきとう",       english: "suitable / appropriate" },
    { id: "n3-16", japanese: "比べる",   reading: "くらべる",       english: "to compare" },
    { id: "n3-17", japanese: "認める",   reading: "みとめる",       english: "to recognize / admit" },
    { id: "n3-18", japanese: "断る",     reading: "ことわる",       english: "to refuse / decline" },
    { id: "n3-19", japanese: "迷う",     reading: "まよう",         english: "to be lost / hesitate" },
    { id: "n3-20", japanese: "驚く",     reading: "おどろく",       english: "to be surprised" },
  ],
  N2: [
    { id: "n2-1",  japanese: "概念",     reading: "がいねん",       english: "concept / notion" },
    { id: "n2-2",  japanese: "傾向",     reading: "けいこう",       english: "tendency / trend" },
    { id: "n2-3",  japanese: "契約",     reading: "けいやく",       english: "contract / agreement" },
    { id: "n2-4",  japanese: "効率",     reading: "こうりつ",       english: "efficiency" },
    { id: "n2-5",  japanese: "根拠",     reading: "こんきょ",       english: "basis / grounds" },
    { id: "n2-6",  japanese: "妥協",     reading: "だきょう",       english: "compromise" },
    { id: "n2-7",  japanese: "手段",     reading: "しゅだん",       english: "means / method" },
    { id: "n2-8",  japanese: "成果",     reading: "せいか",         english: "result / outcome" },
    { id: "n2-9",  japanese: "前提",     reading: "ぜんてい",       english: "premise / assumption" },
    { id: "n2-10", japanese: "段階",     reading: "だんかい",       english: "stage / phase" },
    { id: "n2-11", japanese: "著しい",   reading: "いちじるしい",   english: "remarkable / striking" },
    { id: "n2-12", japanese: "曖昧",     reading: "あいまい",       english: "vague / ambiguous" },
    { id: "n2-13", japanese: "柔軟",     reading: "じゅうなん",     english: "flexible" },
    { id: "n2-14", japanese: "謙虚",     reading: "けんきょ",       english: "humble / modest" },
    { id: "n2-15", japanese: "緻密",     reading: "ちみつ",         english: "precise / detailed" },
    { id: "n2-16", japanese: "促す",     reading: "うながす",       english: "to urge / encourage" },
    { id: "n2-17", japanese: "覆す",     reading: "くつがえす",     english: "to overturn / reverse" },
    { id: "n2-18", japanese: "担う",     reading: "になう",         english: "to bear / shoulder" },
    { id: "n2-19", japanese: "培う",     reading: "つちかう",       english: "to cultivate / foster" },
    { id: "n2-20", japanese: "踏まえる", reading: "ふまえる",       english: "to be based on / consider" },
  ],
  N1: [
    { id: "n1-1",  japanese: "齟齬",     reading: "そご",           english: "discrepancy / gap" },
    { id: "n1-2",  japanese: "忖度",     reading: "そんたく",       english: "reading the room / inferring intent" },
    { id: "n1-3",  japanese: "逡巡",     reading: "しゅんじゅん",   english: "hesitation / vacillation" },
    { id: "n1-4",  japanese: "瑕疵",     reading: "かし",           english: "defect / flaw" },
    { id: "n1-5",  japanese: "蓋然性",   reading: "がいぜんせい",   english: "probability / likelihood" },
    { id: "n1-6",  japanese: "恣意的",   reading: "しいてき",       english: "arbitrary / capricious" },
    { id: "n1-7",  japanese: "帰結",     reading: "きけつ",         english: "conclusion / consequence" },
    { id: "n1-8",  japanese: "相殺",     reading: "そうさい",       english: "offset / cancellation" },
    { id: "n1-9",  japanese: "敷衍",     reading: "ふえん",         english: "elaboration / expansion" },
    { id: "n1-10", japanese: "捨象",     reading: "しゃしょう",     english: "abstraction / omission" },
    { id: "n1-11", japanese: "鑑みる",   reading: "かんがみる",     english: "to consider / in light of" },
    { id: "n1-12", japanese: "醸し出す", reading: "かもしだす",     english: "to create / give off (atmosphere)" },
    { id: "n1-13", japanese: "孕む",     reading: "はらむ",         english: "to contain / be fraught with" },
    { id: "n1-14", japanese: "嚆矢",     reading: "こうし",         english: "the beginning / first instance" },
    { id: "n1-15", japanese: "敷衍",     reading: "ふえん",         english: "to expand / elaborate on" },
    { id: "n1-16", japanese: "逼迫",     reading: "ひっぱく",       english: "pressing / urgent" },
    { id: "n1-17", japanese: "乖離",     reading: "かいり",         english: "divergence / gap" },
    { id: "n1-18", japanese: "濫用",     reading: "らんよう",       english: "misuse / abuse" },
    { id: "n1-19", japanese: "紆余曲折", reading: "うよきょくせつ", english: "twists and turns / complications" },
    { id: "n1-20", japanese: "一石二鳥", reading: "いっせきにちょう", english: "killing two birds with one stone" },
  ],
};

export const LEVEL_META: Record<JLPTLevel, { color: string; bg: string; description: string }> = {
  N5: { color: "#30C06E", bg: "#E8F7EE", description: "Absolute beginner" },
  N4: { color: "#4C8BF5", bg: "#E6F0FF", description: "Elementary" },
  N3: { color: "#FF9340", bg: "#FFE8CC", description: "Intermediate" },
  N2: { color: "#9C5FD6", bg: "#F0E8FF", description: "Upper intermediate" },
  N1: { color: "#E84040", bg: "#FFE8E8", description: "Advanced" },
};
